label_smoothing: 0.0
lr: 5.0e-05
model_hparams:
  Classifier: Classifier
  loss: bce
  num_classes: 13
  outnorm: false
  pretrained: true
model_name: swin_base_patch4_window7_224.ms_in22k
use_mixup: false
