dataset:
  name: "MIMIC_Img_Dataset"
  h5_file_path:
    train: "dataset/emb_train_data_v2.h5"
    val: "dataset/emb_val_data_v2.h5"
    test: "dataset/emb_test_data_v2.h5"
  imgpath: "../physionet.org/files/mimic-cxr-jpg/2.1.0/files"
  csvpath: "../physionet.org/files/mimic-cxr-jpg/2.1.0/mimic-cxr-2.0.0-chexpert.csv.gz"
  metacsvpath: "../physionet.org/files/mimic-cxr-jpg/2.1.0/mimic-cxr-2.0.0-metadata.csv.gz"
  splitcsvpath: "../physionet.org/files/mimic-cxr-jpg/2.1.0/mimic-cxr-2.0.0-split.csv.gz"
  text_path:
    train: "dataset/text_train_data_noimpression.h5"
    val: "dataset/text_val_data_noimpression.h5"
    test: "dataset/text_test_data_noimpression.h5"
  img_h5_path:
    train: "dataset/img_train_data.h5"
    val: "dataset/img_val_data.h5"
    test: "dataset/img_test_data.h5"
  transforms: true

dataloader:
  batch_size: 64
  num_workers: 32

model:
  name: "resnet50"
  params:
    outnorm: false
    num_classes: 13
    pretrained: true
    loss: "bce"
    Classifier: "Classifier"

train:
  label_smoothing: 0.0
  epochs: 50
  use_mixup: false

optimizer:
  lr: 0.00005
